# Generated by Django 2.0.1 on 2018-08-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180812_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='teachers',
            field=models.IntegerField(default=0),
        ),
    ]
