# Generated by Django 2.0.1 on 2018-08-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20180818_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='teachers',
        ),
    ]
